### ISSUE TITLE
\InvalidDataTypeException: yaml_parse()

### ISSUE THREAD

**Issue by ikorgik** [e0ipso/data_model#1]
Hi, I have an error during module installation:

`Drupal\Component\Serialization\Exception\InvalidDataTypeException: yaml_parse(): scanning error encountered during parsing: found character that cannot start any token (line 14, column 9), context while scanning for the next token (line 14, column 9) in /var/www/html/web/core/lib/Drupal/Component/Serialization/YamlPecl.php on line 63`

That's because 'data_model.services.yml' (line: 13) has wrong arguments format.

Also this module requires 'rest' module in dependencies.
`Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service         [error]
"serializer.normalizer.data_reference_definition.schema_json.hal_json" has a dependency on
a non-existent service "rest.link_manager"`

I will provide a patch to fix.

**Comment by e0ipso** [comment]
This was fixed.
